/*
 * Copyright (C) 2003-2008  Gretti N'Guessan, Nicolas Ribot
 *
 * This file is part of GeoAdminSuite
 *
 * GeoAdminSuite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GeoAdminSuite is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with GeoAdminSuite.  If not, see <http://www.gnu.org/licenses/>.
 */

/*


 * RasterRegistrarApp.java


 *


 * Created on 6 mars 2002, 16:25


 */


 


package org.geogurus.raster.gui;


import java.util.ResourceBundle;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import org.geogurus.raster.RasterRegistrar;


/**


 * This frame defines the gui application access for


 * register rasters in database.


 * @author Bastien VIALADE


 */ 


public class RasterRegistrarFrame extends javax.swing.JFrame {


    private RasterRegistrar rasterRegistrar ;


    // This panel manages a RasterRegistrar object


    private RasterRegistrarPanel rasterRegistrarPanel ;


    private RasterRegistrarHelp rasterRegistrarHelp ;


    private ResourceBundle res;


    


    /** Creates new form RasterRegistrarApp


     * Inits gui environment.


     */


    public RasterRegistrarFrame() {


        res = ResourceBundle.getBundle("../../../../resources/org/geogurus/raster/gui/RasterRegistrarFrame") ;


        initComponents();


        try {


            ImageIcon icon = new ImageIcon(getClass().getResource("/images/logo_scot.jpg")) ;


            this.setIconImage(icon.getImage()) ;


        } catch (Exception ex) {


            System.out.println("Can't display icon");


        }


        // Creates a new rasterRegistrar to complete


        rasterRegistrar = new RasterRegistrar() ;


        rasterRegistrarPanel = new RasterRegistrarPanel() ;


        rasterRegistrarPanel.setData(rasterRegistrar) ;


        jPanel1.add(rasterRegistrarPanel) ;


        rasterRegistrarHelp = new RasterRegistrarHelp(this, true);


    } 


    


    /** This method is called from within the constructor to


     * initialize the form.


     * WARNING: Do NOT modify this code. The content of this method is


     * always regenerated by the Form Editor.


     */


    private void initComponents() {//GEN-BEGIN:initComponents


        jPanel1 = new javax.swing.JPanel();


        jPanel2 = new javax.swing.JPanel();


        jButton1 = new javax.swing.JButton();


        jButton2 = new javax.swing.JButton();


        jPanel3 = new javax.swing.JPanel();


        jLabel1 = new javax.swing.JLabel();


        jLabel2 = new javax.swing.JLabel();


        menuBar = new javax.swing.JMenuBar();


        fileMenu = new javax.swing.JMenu();


        exitMenuItem = new javax.swing.JMenuItem();


        helpMenu = new javax.swing.JMenu();


        contentsMenuItem = new javax.swing.JMenuItem();


        aboutMenuItem = new javax.swing.JMenuItem();





        getContentPane().setLayout(new java.awt.BorderLayout(0, 15));





        setTitle(res.getString("title"));


        addWindowListener(new java.awt.event.WindowAdapter() {


            public void windowClosing(java.awt.event.WindowEvent evt) {


                exitForm(evt);


            }


        });





        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);





        jButton1.setText(res.getString("launchButton"));


        jButton1.addActionListener(new java.awt.event.ActionListener() {


            public void actionPerformed(java.awt.event.ActionEvent evt) {


                rasterAction(evt);


            }


        });





        jPanel2.add(jButton1);





        jButton2.setText(res.getString("CancelButton"));


        jButton2.addActionListener(new java.awt.event.ActionListener() {


            public void actionPerformed(java.awt.event.ActionEvent evt) {


                cancel(evt);


            }


        });





        jPanel2.add(jButton2);





        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);





        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));





        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.gif")));


        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);


        jPanel3.add(jLabel1);





        jLabel2.setText(res.getString("largeTitle"));


        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24));


        jPanel3.add(jLabel2);





        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);





        fileMenu.setText(res.getString("File"));


        exitMenuItem.setText(res.getString("Exit"));


        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {


            public void actionPerformed(java.awt.event.ActionEvent evt) {


                exitMenuItemActionPerformed(evt);


            }


        });





        fileMenu.add(exitMenuItem);


        menuBar.add(fileMenu);


        helpMenu.setText(res.getString("Help"));


        contentsMenuItem.setText(res.getString("Contents"));


        contentsMenuItem.addActionListener(new java.awt.event.ActionListener() {


            public void actionPerformed(java.awt.event.ActionEvent evt) {


                contentAction(evt);


            }


        });





        helpMenu.add(contentsMenuItem);


        aboutMenuItem.setText(res.getString("About"));


        helpMenu.add(aboutMenuItem);


        menuBar.add(helpMenu);


        setJMenuBar(menuBar);





        pack();


    }//GEN-END:initComponents





    private void contentAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentAction


        rasterRegistrarHelp.setVisible(true); ;


    }//GEN-LAST:event_contentAction


    


    /** Execution button pressed. Let's store all rasters */


    private void rasterAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rasterAction


        // Check in the main panel, if rasters values are OK


//        if (!rasterRegistrarPanel.check()) return ;


        // Gets the RasterRegistrar Object with needed parameters


        rasterRegistrar = rasterRegistrarPanel.getData(rasterRegistrar) ;


        // check is OK so params are valids


        rasterRegistrar.setParamValid(true) ;


        //Let's start to register 


        if (rasterRegistrar.register()) { 


            // Well done, everything has been registered


            JOptionPane.showMessageDialog(this,rasterRegistrar.getMessage(),res.getString("Registring_Done_Title"),JOptionPane.INFORMATION_MESSAGE) ;


        } else {


            // Ooops, what's wrong ? 


            JOptionPane.showMessageDialog(this,rasterRegistrar.getMessage(),res.getString("Registring_Error_Title"),JOptionPane.ERROR_MESSAGE) ;


            rasterRegistrar.clearFilesList() ;


        }


    }//GEN-LAST:event_rasterAction


    


    /** Cancel button  pressed */


    private void cancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel


        System.exit(0);


    }//GEN-LAST:event_cancel


    


/** Exit the Application */    


    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed


        System.exit(0);


    }//GEN-LAST:event_exitMenuItemActionPerformed


    


    /** Exit the Application */


    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm


        System.exit(0);


    }//GEN-LAST:event_exitForm


    


    /** Call this main to start this gui application


     * @param args the command line arguments - No args needed


     */


    public static void main(String args[]) {


        RasterRegistrarFrame frame = new RasterRegistrarFrame();


        frame.pack() ;


        frame.setVisible(true); ;


    }


    


    // Variables declaration - do not modify//GEN-BEGIN:variables


    private javax.swing.JMenuItem aboutMenuItem;


    private javax.swing.JMenu helpMenu;


    private javax.swing.JMenuBar menuBar;


    private javax.swing.JButton jButton2;


    private javax.swing.JButton jButton1;


    private javax.swing.JMenuItem contentsMenuItem;


    private javax.swing.JMenuItem exitMenuItem;


    private javax.swing.JLabel jLabel2;


    private javax.swing.JLabel jLabel1;


    private javax.swing.JPanel jPanel3;


    private javax.swing.JPanel jPanel2;


    private javax.swing.JPanel jPanel1;


    private javax.swing.JMenu fileMenu;


    // End of variables declaration//GEN-END:variables


    


}


