/*
 * RGB.java
 *
 * Created on 20 mars 2002, 10:11
 */

package org.geogurus.mapserver.objects;

import org.geogurus.tools.string.ConversionUtilities;

/**
 * This class defines a simple RGB object
 *
 * @author  Bastien VIALADE
 */
public class RGB  implements java.io.Serializable {
    
    private int red;
    private int green;
    private int blue;
    
    
    /** Empty constructor */
    public  RGB() {
        this(0,0,0);
    }
    
    /** Creates a new instance of RGB */
    public RGB(int red_, int green_, int blue_) {
        red = red_;
        green = green_;
        blue = blue_;
    }
    /**
     * Creates a new instance of RGB with the given string, containing space-separated RGB values,
     * as int. Should only be used by servlets receiving this string as a JS-controled parameter,
     * for example generated by the colorChooser.
     */
    public RGB(String col) {
        java.util.StringTokenizer tok = new java.util.StringTokenizer(col);
        try {
            red = new Integer(tok.nextToken()).intValue();
            green = new Integer(tok.nextToken()).intValue();
            blue = new Integer(tok.nextToken()).intValue();
        } catch (NumberFormatException nfe) {
            // default color
            red =0;green=0;blue=0;
        }
    }
    
    /** Get methods to get an RGB tab or individual color value*/
    public int[] getRGB() {
        int[] rgb = {red,green,blue};
        return rgb;
    }
    
    public int getRed()     {return red;}
    public int getGreen()   {return green;}
    public int getBlue()    {return blue;}
    
    /** Set methods to changes RGB values*/
    public void setRed(int red_)        {red = red_;}
    public void setGreen(int green_)    {green = green_;}
    public void setBlue(int blue_)      {blue = blue_;}
    
    
    /** Loads data from file
     * and fill Object parameters with.
     * @param br BufferReader containing file data to read
     * @return true is mapping done correctly
     */    
    public synchronized boolean load(String[] tokens) {
        if (tokens.length<4) return false;
        try {
            red     = Integer.parseInt(ConversionUtilities.removeDoubleQuotes(tokens[1]));
            green   = Integer.parseInt(tokens[2]);
            blue    = Integer.parseInt(ConversionUtilities.removeDoubleQuotes(tokens[3]));
        } catch (NumberFormatException nfe) {
            System.err.println("Can't cast color: "+nfe);
            return false;
        }
        return true;
    }
    
    /**  Saves RGB object to the given BufferedWriter
     * with MapFile style.
     */
   public synchronized boolean saveAsMapFile(java.io.BufferedWriter bw) {
       boolean result = true;
        try {
            bw.write(red+" "+green+" "+blue+"\n");
        } catch (Exception ex) {
            ex.printStackTrace();
            return false;
        }
       return result;
   }
    
     /** Returns a string representation of the RGB Object
      * @return a string representation of the RGB Object.
      */     
    public String toString() {
        /*
        return "RGB OBJECT: "+
               "\n  . Red   = "+red+
               "\n  . Green = "+green+
               "\n  . Blue  = "+blue+"\n";
         */
        return "" + red + " " + green + " " + blue;
    }
    
}

