/*
 * FreeArrowDemo.java
 *
 * Created on 18 mars 2002, 15:20
 */

package org.geogurus.tools.graphics;

/**
 *
 * @author  Bastien VIALADE
 */

public class FreeArrowFrameDemo extends java.awt.Frame {
    
private FreeArrowCanvas freeArrowCanvas ;

    /** Creates new form FreeArrowDemo */
    public FreeArrowFrameDemo() {
        initComponents();
        add(new FreeArrowPanelDemo());  
    }
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setBackground(java.awt.Color.cyan);
        setTitle("FreeArrowDemo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }//GEN-END:initComponents
                 
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0); 
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.Frame f = new FreeArrowFrameDemo();
        f.setSize(500,600);
        f.setVisible(true);; 
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}

