/*
* 
*  The JUMP DB Query Plugin is Copyright (C) 2007  Larry Reeder
*  JUMP is Copyright (C) 2003 Vivid Solutions
* 
*  This file is part of the JUMP DB Query Plugin.
*  
*  The JUMP DB Query Plugin is free software; you can redistribute it and/or 
*  modify it under the terms of the Lesser GNU General Public License as 
*  published *  by the Free Software Foundation; either version 3 of the 
*  License, or  (at your option) any later version.
*  
*  This software is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  Lesser GNU General Public License for more details.
*  
*  You should have received a copy of the GNU General Public License
*  along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
package org.freevoice.jumpdbqueryextension.ui;

import javax.swing.*;
import java.awt.*;

/**
 *
 */
public class QueryForm
{
    private JPasswordField password = null;
    private JTextField username = null;
    private JTextArea query = null;
    private JTextField jdbcUrl = null;


    private JPanel queryPanel = null;

    private JLabel jdbcUrlLabel = null;
    private JLabel usernameLabel = null;
    private JLabel passwordLabel = null;
    private JButton button1;

    public String getPassword()
    {
        return new String(password.getPassword());
    }

    public void setPassword(JPasswordField password)
    {
        this.password = password;
    }


    public String getUsername()
    {
        return username.getText();
    }

    public void setUsername(JTextField username)
    {
        this.username = username;
    }

    public String getQuery()
    {
        return query.getText();
    }

    public void setQuery(JTextArea query)
    {
        this.query = query;
    }

    public String getJdbcUrl()
    {
        return jdbcUrl.getText();
    }

    public void setJdbcUrl(JTextField jdbcUrl)
    {
        this.jdbcUrl = jdbcUrl;
    }


    //
    // WARNING!  WARNING!  WARNING!  WARNING!  WARNING!  WARNING!  WARNING!
    // 
    //     THIS CODE IN THIS BLOCK IS AUTOMATICALLY GENERATED BY THE GUI SOURCE 
    //     PLUGIN.  ANY CHNAGE TO THIS CODE WILL BE OVER WRITTEN 
    //     THE NEXT TIME THIS CODE IS GENERATED.
    // 
    // WARNING!  WARNING!  WARNING!  WARNING!  WARNING!  WARNING!  WARNING!
    //

    {
        _initGeneratedUICode();
    }

    //
    // WARNING!  WARNING!  WARNING!  WARNING!  WARNING!  WARNING!  WARNING!  WARNING!
    // 
    //     THIS CODE IN _initGeneratedUICode() IS AUTOMATICALLY GENERATED BY THE GUI 
    //     SOURCE PLUGIN.  ANY CHNAGE TO THIS CODE WILL BE OVER WRITTEN
    //     THE NEXT TIME THIS CODE IS GENERATED.
    // 
    // WARNING!  WARNING!  WARNING!  WARNING!  WARNING!  WARNING!  WARNING!  WARNING!
    //

    private void _initGeneratedUICode() {

        javax.swing.Box.Filler	tmpSpacer;



        queryPanel = new javax.swing.JPanel();
        queryPanel.setLayout(new java.awt.GridBagLayout());


        query = new javax.swing.JTextArea();
        query.setText("");
        queryPanel.add(query, new java.awt.GridBagConstraints(0, 0, 2, 1, 0.0, 0.0 ,GridBagConstraints.CENTER,
													 GridBagConstraints.BOTH, new java.awt.Insets(0, 0, 0, 0), 0, 0));
        query.setPreferredSize(new java.awt.Dimension(150, 50));


        jdbcUrlLabel = new javax.swing.JLabel();
        jdbcUrlLabel.setText("JDBC Url:");
        queryPanel.add(jdbcUrlLabel, new java.awt.GridBagConstraints(0, 1, 1, 1, 0.0, 0.0 ,GridBagConstraints.WEST,
													 GridBagConstraints.NONE, new java.awt.Insets(0, 0, 0, 0), 0, 0));


        username = new javax.swing.JTextField();
        username.setEnabled(true);
        queryPanel.add(username, new java.awt.GridBagConstraints(1, 2, 1, 1, 0.0, 0.0 ,GridBagConstraints.WEST,
													 GridBagConstraints.HORIZONTAL, new java.awt.Insets(0, 0, 0, 0), 0, 0));
        username.setPreferredSize(new java.awt.Dimension(150, -1));


        passwordLabel = new javax.swing.JLabel();
        passwordLabel.setText("Password");
        queryPanel.add(passwordLabel, new java.awt.GridBagConstraints(0, 3, 1, 1, 0.0, 0.0 ,GridBagConstraints.WEST,
													 GridBagConstraints.NONE, new java.awt.Insets(0, 0, 0, 0), 0, 0));


        jdbcUrl = new javax.swing.JTextField();
        jdbcUrl.setEnabled(true);
        queryPanel.add(jdbcUrl, new java.awt.GridBagConstraints(1, 1, 1, 1, 0.0, 0.0 ,GridBagConstraints.WEST,
													 GridBagConstraints.HORIZONTAL, new java.awt.Insets(0, 0, 0, 0), 0, 0));
        jdbcUrl.setPreferredSize(new java.awt.Dimension(150, -1));


        password = new javax.swing.JPasswordField();
        queryPanel.add(password, new java.awt.GridBagConstraints(1, 3, 1, 1, 0.0, 0.0 ,GridBagConstraints.WEST,
													 GridBagConstraints.HORIZONTAL, new java.awt.Insets(0, 0, 0, 0), 0, 0));
        password.setPreferredSize(new java.awt.Dimension(150, -1));


        usernameLabel = new javax.swing.JLabel();
        usernameLabel.setText("User name (nico)");
        queryPanel.add(usernameLabel, new java.awt.GridBagConstraints(0, 2, 1, 1, 0.0, 0.0 ,GridBagConstraints.WEST,
													 GridBagConstraints.NONE, new java.awt.Insets(0, 0, 0, 0), 0, 0));


        button1 = new javax.swing.JButton();
        button1.setText("Run Query");
        button1.setToolTipText("Submit query to database");
        queryPanel.add(button1, new java.awt.GridBagConstraints(1, 4, 1, 1, 0.0, 0.0 ,GridBagConstraints.CENTER,
													 GridBagConstraints.HORIZONTAL, new java.awt.Insets(0, 0, 0, 0), 0, 0));

    }


}
