/*
 * RasterRegistrarHelp.java
 *
 * Created on 7 mars 2002, 19:05
 */

package org.geogurus.raster.gui;
import java.util.ResourceBundle;

import javax.swing.JLabel;

/**
 * This class displays application usage
 * @author Bastien VIALADE
 */
public class RasterRegistrarHelp extends javax.swing.JDialog {
    private ResourceBundle res ;
    
    /** Creates new form RasterRegistrarHelp
     * @param parent Main frame
     * @param modal Is this frame modal ?
     */
    public RasterRegistrarHelp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Displays usage
        JLabel jLabel ;
       try {
            res = ResourceBundle.getBundle("resources/RasterRegistrar") ;
            String line;
            int lineNumber = Integer.parseInt(res.getString("usageLength")) ;
            jPanel3.setLayout(new java.awt.GridLayout(lineNumber,1,3,3)) ;
             for (int i=0; i<lineNumber; i++) {
                jLabel = new JLabel("   "+res.getString("usage."+i)) ;
                jPanel3.add(jLabel) ;
            }
               pack();
         } catch (Exception e) {
            jLabel = new JLabel("Can't read usage from resource file") ;
            jPanel3.add(jLabel) ;
        }
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        getContentPane().setLayout(new java.awt.BorderLayout(30, 50));

        setTitle("USAGE");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 18));
        jLabel1.setText("Raster Registring usage");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAction(evt);
            }
        });

        jPanel2.add(jButton1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    private void closeAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAction
        this.closeDialog(null) ;
    }//GEN-LAST:event_closeAction
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /** Only for test
     * @param args no args needed
     */
    public static void main(String args[]) {
        new RasterRegistrarHelp(new javax.swing.JFrame(), true).setVisible(true);;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}

