#!/bin/bash

################################################################################
#
# Shell script to apply the configuration
#
################################################################################

################################################################################
#  Configuration variable:
# Edit the following variable to match target environment
################################################################################

cd `dirname $0`

if [ ! -f "config-$1.txt" ]; then
    echo "cannot find file config-$1.txt, aborting"
    exit 1
fi

source "config-$1.txt"
PROJECT_DIR=$(cd `dirname $0` && pwd)

# Shortcut variable to hold common PG connection parameters
export PGCON="-h $DBHOST -U $DBUSER -p $DBPORT"

patchfile() {
  from="$1"
  to="$2"
  echo ">> Patching $from to $to"
  echo "#!/bin/bash
## THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT DIRECTLY !!!
## INSTEAD EDIT $from
## and rerun $PROJECT_DIR/scripts/install.sh" > $to
  
  if [ -z $TC_OVERRIDE_URL ]; then
      TC_WMS_URL="http://$SERVERNAME/wms/geosignal"
  else
      TC_WMS_URL="$TC_OVERRIDE_URL"
  fi

  sed \
    -e "s#%PGCON%#$PGCON#g" \
    -e "s#%DBHOST%#$DBHOST#g" \
    -e "s#%DBPORT%#$DBPORT#g" \
    -e "s#%DBNAME%#$DBNAME#g" \
    -e "s#%DBUSER%#$DBUSER#g" \
    -e "s#%DBPASS%#$DBPASS#g" \
    -e "s#%DATADIR%#$DATADIR#g" \
    -e "s#%PGBIN%#$PGBIN#g" \
    "$from" >> "$to"
}

cd ""


patchfile "$PROJECT_DIR/create_database.sh.in" "$PROJECT_DIR/create_database.sh"
#patchfile "$PROJECT_DIR/sql_scripts/admin.sql.in" "$PROJECT_DIR/sql_scripts/admin.sql"

echo
echo "Configuration applied:"
echo "database host: $DBHOST"
echo "database port: $DBPORT"
echo "database user: $DBUSER"
echo "database name: $DBNAME"
echo "PostgreSQL binary directory : $PGBIN"
echo
echo "Navstreet data directory:"
ls -al $DATADIR
echo