#!/bin/bash
## THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT DIRECTLY !!!
## INSTEAD EDIT /Users/nicolas/Projets/nvq/create_database.sh.in
## and rerun /Users/nicolas/Projets/nvq/scripts/install.sh
#!/bin/bash

################################################################################
#
# Shell script to create the postgis database that will receive Navstreets data
#
# TODO: factorize
################################################################################

# These variables will be replaced by configuration values after running applu_config.sh
DBHOST=localhost
DBPORT=5432
DBNAME=nvq
DBUSER=nicolas
DBPASS=
DATADIR=/Volumes/Lucifer/data
PGBIN=

echo

echo "Dropping the database $DBNAME if exists..."
${PGBIN}dropdb --if-exists  $DBCON  $DBNAME
OUT=$?

if [ $OUT -eq 0 ];then
    echo "  >> Database $DBAME dropped if it existed."
else
    echo "  >> Unable to drop database $DBNAME"
    echo "  >> exiting"
    echo 
    exit 1
fi
echo

echo "Creating database $DBNAME..."
${PGBIN}createdb  $DBCON -E UTF-8 $DBNAME
OUT=$?

if [ $OUT -eq 0 ];then
    echo "  >> Database $DBANE created."
else
    echo "  >> Unable to create database $DBNAME"
    echo "  >> exiting"
    echo 
    exit 1
fi
echo

echo "Installing Postgis through Extension..."
${PGBIN}psql  $DBCON -c "create extension postgis" -d $DBNAME
OUT=$?

if [ $OUT -eq 0 ];then
    echo "  >> Postgis extension created"
    ${PGBIN}psql  $DBCON -t -c "select postgis_full_version() UNION select version() order by 1 desc" -d $DBNAME
else
    echo "  >> Unable to create postgis extension, aborting."
    echo "  >> exiting"
    echo 
    exit 1
fi

echo
echo "Done with database creation"
echo

