CREATE TABLE ident_new
(
UU99	VARCHAR(20) NOT NULL,
ID	INTEGER  PRIMARY KEY,
DC	VARCHAR(20) NOT NULL,
IRIS	VARCHAR(20) NOT NULL,
IDENT	VARCHAR(20) NOT NULL,
NOTEL	VARCHAR(20) NOT NULL,
ID_NEW	INTEGER,
ARESIMULER	REAL,
ARESIMUL_A	REAL,
N_BREAK	INTEGER,
PART	REAL,
FILTER__	INTEGER
);